namespace: "netapp"
name: "um_info"
version: "21.8.1"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license_file: COPYING
readme: README.md
description: NetApp Unified Manager(AIQUM 9.7) Collection
repository: https://github.com/ansible-collections/netapp.um_info
issues: https://github.com/ansible-collections/netapp.um_info/issues
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - netapp
    - aiqum
    - um
    - ontap
