namespace: "netapp"
name: "um_info"
version: "20.5.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: NetApp Unified Manager(AIQUM 9.7/OCUM) Collection
repository: https://github.com/ansible-collections/netapp
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
